spring:
  application: 
    name: gateway-server
  cloud:
    loadbalancer:
      configurations: health-check
    gateway: # Declaracion de los paths mediante SC API Gateway
      routes:
        - id: hotel-service
          uri: lb://hotel-service # lb es por Load Balancer
          predicates:
            - Path=/api/hotels/**
          filters:
            - StripPrefix=2
        # Add a simple re-route from: /get to: http://httpbin.org:80
        - id: add_request_header_route
          uri: http://httpbin.org:80 # forward to httpbin
          predicates:
            - Path=/get # filtra todos los request a este path
          filters: # Add a simple "Hello:World" HTTP Header
            #  // add header
            - AddRequestHeader=Hello, World
            - AddRequestHeader=X-Request-Foo, Bar
        - id: rooms-service
          uri: lb://rooms-service
          predicates:
            - Path=/api/rooms/**
#          filters:
#            - StripPrefix=2
#            - AddRequestHeader=token-request, 123456
#            - AddResponseHeader=token-response, 12345678
#            - SetResponseHeader=Content-Type, text/plain
#            - AddRequestParameter=nombre, andres

# Se indica la url del servidor de eureka, esto para cuando el servidor esta en otra ruta
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    # lb mediante eureka
    webclient:
      enabled: true
    fetchRegistry: true
    registerWithEureka: false
  instance:
    preferIpAddress: true