# Se hace un LB con Eureka integration (+complex, dynamic)
spring:
  cloud:
    loadbalancer:
      configurations: health-check
#    discovery:
#      enabled: true
    gateway:
#      httpclient:
#        wiretap: true
      routes: # Declaracion de los paths mediante SC API Gateway
        - id: hotels-microservice
          uri: lb://hotels-microservice # lb es por Load Balancer
          predicates:
            - Path=/api/hotels/**
          filters:
            - StripPrefix=2
        - id: ms-guest
          uri: lb://ms-guest # lb es por Load Balancer
          predicates:
            - Path=/api/guest/**
          filters:
            - StripPrefix=2
        # Add a simple re-route from: /get to: http://httpbin.org:80
        - id: add_request_header_route
          uri: http://httpbin.org:80 # forward to httpbin
          predicates:
            - Path=/get # filtra todos los request a este path
          filters: # Add a simple "Hello:World" HTTP Header
            #  // add header
            - AddRequestHeader=Hello, World
            - AddRequestHeader=X-Request-Foo, Bar
        - id: rooms-service
          uri: lb://rooms-service
          predicates:
            - Path=/api/rooms/** # Declaracion de los paths mediante SC API Gateway
#          filters:
#            - StripPrefix=2
#            - AddRequestHeader=token-request, 123456
#            - AddResponseHeader=token-response, 12345678
#            - SetResponseHeader=Content-Type, text/plain
#            - AddRequestParameter=nombre, andres
