server:
  port: 8090

spring:
  application: 
    name: gateway-server
  cloud:
    gateway: # Declaracion de los paths mediante SC API Gateway
      routes:
        - id: hotel-service
          uri: lb://hotel-service # lb es por Load Balancer
          predicates:
            - Path=/api/hotels/**
          filters:
            - StripPrefix=2
        - id: rooms-service
          uri: lb://rooms-service
          predicates:
            - Path=/api/rooms/**
#          filters:
#            - StripPrefix=2
#            - AddRequestHeader=token-request, 123456
#            - AddResponseHeader=token-response, 12345678
#            - SetResponseHeader=Content-Type, text/plain
#            - AddRequestParameter=nombre, andres

# Se indica la url del servidor de eureka, esto para cuando el servidor esta en otra ruta
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

